backend/autorizzazioni/urls.py
from django.urls import path
from .views import (autorizzazioni_home, 
                    AutorizzazioneCreateView, AutorizzazioneUpdateView, delete_autorizzazione,
                    DettaglioScadenzaAutorizzazioneCreateView, DettaglioScadenzaAutorizzazioneUpdateView, delete_dettaglio_autorizzazione,
                    ParametroAutorizzazioneCreateView, ParametroAutorizzazioneUpdateView, delete_parametro,
                    CampoApplicazioneCreateView, CampoApplicazioneUpdateView, delete_campo_applicazione,
                    DettaglioCampoApplicazioneCreateView, DettaglioCampoApplicazioneUpdateView, delete_dettaglio_campo_applicazione,
                    tabelle_generiche_autorizzazioni,
                    stampa_registro_autorizzazioni,
                    
                    )

app_name="autorizzazioni"

urlpatterns = [
    
    # Home Autorizzazioni
    path('', autorizzazioni_home, name='autorizzazioni_home'),    

    # Manage Autorizzazioni
    path('crea_autorizzazione/', AutorizzazioneCreateView.as_view(), name="crea_autorizzazione"), 
    path('modifica_autorizzazione/<int:pk>/', AutorizzazioneUpdateView.as_view(), name="modifica_autorizzazione"), 
    path('delete_autorizzazione/<int:pk>', delete_autorizzazione, name="delete_autorizzazione"),

    # Manage Rinnovi
    path('<int:fk_autorizzazione>/aggiungi_dettaglio_autorizzazione/', DettaglioScadenzaAutorizzazioneCreateView.as_view(), name="aggiungi_dettaglio_autorizzazione"), 
    path('<int:fk_autorizzazione>/modifica_dettaglio_autorizzazione/<int:pk>/', DettaglioScadenzaAutorizzazioneUpdateView.as_view(), name="modifica_dettaglio_autorizzazione"), 
    path('delete_dettaglio_autorizzazione/<int:pk>', delete_dettaglio_autorizzazione, name="delete_dettaglio_autorizzazione"),

    # Tabelle generiche
    path('tabelle_generiche_autorizzazioni/', tabelle_generiche_autorizzazioni, name="tabelle_generiche_autorizzazioni"),

    # Manage Parametri
    path('crea_parametro/', ParametroAutorizzazioneCreateView.as_view(), name="crea_parametro"), 
    path('modifica_parametro/<int:pk>/', ParametroAutorizzazioneUpdateView.as_view(), name="modifica_parametro"), 
    path('delete_parametro/<int:pk>', delete_parametro, name="delete_parametro"),

    # Manage Campi Applicazione
    path('crea_campo_applicazione/', CampoApplicazioneCreateView.as_view(), name="crea_campo_applicazione"), 
    path('modifica_campo_applicazione/<int:pk>/', CampoApplicazioneUpdateView.as_view(), name="modifica_campo_applicazione"), 
    path('delete_campo_applicazione/<int:pk>', delete_campo_applicazione, name="delete_campo_applicazione"),

    # Manage Dettaglio Campi Applicazione
    path('<int:fk_campoapplicazione>/aggiungi_dettaglio_campo_applicazione/', DettaglioCampoApplicazioneCreateView.as_view(), name="aggiungi_dettaglio_campo_applicazione"), 
    path('<int:fk_campoapplicazione>/modifica_dettaglio_campo_applicazione/<int:pk>/', DettaglioCampoApplicazioneUpdateView.as_view(), name="modifica_dettaglio_campo_applicazione"), 
    path('delete_dettaglio_campo_applicazione/<int:pk>', delete_dettaglio_campo_applicazione, name="delete_dettaglio_campo_applicazione"),

    # Stampe
    path('stampa_registro_autorizzazioni/', stampa_registro_autorizzazioni, name="stampa_registro_autorizzazioni"), 
]

backend/lwg/urls.py
from django.urls import path
from lwg.views import (lwg_home, lwg_procedure, scadenzario_completo
                                    )

app_name="lwg"

urlpatterns = [
    
    # Home LWG
    path('', lwg_home, name='lwg_home'),
    
    #LWG Procedure    
    path('lwg_procedure/<int:fk_lwgsection>', lwg_procedure, name='lwg_procedure'),

    # Scadenzario    
    path('scadenzario_completo/', scadenzario_completo, name='scadenzario_completo'),    

    
]

backend/qmsproject/urls.py
from core.views import home
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("", home, name="home"),
    path("core/", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("anagrafiche/", include("anagrafiche.urls")),
    path("human_resources/", include("human_resources.urls")),
    path("acquistopelli/", include("acquistopelli.urls")),
    path("articoli/", include("articoli.urls")),
    path("manualeprocedure/", include("manualeprocedure.urls")),
    path("monitoraggi/", include("monitoraggi.urls")),
    path("manutenzioni/", include("manutenzioni.urls")),
    path("lwg/", include("lwg.urls")),
    path("autorizzazioni/", include("autorizzazioni.urls")),
    path("gestionerifiuti/", include("gestionerifiuti.urls")),
    path("nonconformity/", include("nonconformity.urls")),
    path("chem_man/", include("chem_man.urls")),
    path("antincendio/", include("antincendio.urls")),
    path("ricette/", include("ricette.urls")),
    path("air_emissions/", include("air_emissions.urls")),
    path("vendite/", include("vendite.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    # API
    path("api/accounts/", include("accounts.urls")),
    path("api/anagrafiche/", include("anagrafiche.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/autorizzazioni/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages


from .models import *
from .forms import *
from .filters import AutorizzazioneFilter


def autorizzazioni_home(request):
    autorizzazioni = Autorizzazione.objects.all()
    autorizzazione_filter = AutorizzazioneFilter(request.GET, queryset=Autorizzazione.objects.all())
    page = request.GET.get('page', 1)
    paginator = Paginator(autorizzazioni, 50)
    
    try:
        autorizzazioni_home = paginator.page(page)
    except PageNotAnInteger:
        autorizzazioni_home = paginator.page(1)
    except EmptyPage:
        autorizzazioni_home = paginator.page(paginator.num_pages)
    context={
        'autorizzazioni_home': autorizzazioni_home,
        'filter': autorizzazione_filter,
        
    }
    return render(request, "autorizzazioni/autorizzazioni_home.html", context)



def tabelle_generiche_autorizzazioni(request):
    parametri = ParametroAutorizzazione.objects.all()
    campi_applicazione = CampoApplicazione.objects.all()

    context = {'parametri': parametri, 
               'campi_applicazione': campi_applicazione,                           
                }
    
    return render(request, "autorizzazioni/tabelle_generiche_autorizzazioni.html", context)


class AutorizzazioneCreateView(LoginRequiredMixin,CreateView):
    model = Autorizzazione
    form_class = AutorizzazioneModelForm
    template_name = 'autorizzazioni/autorizzazione.html'
    success_message = 'Autorizzazione aggiunta correttamente!'
    

    def get_success_url(self):        
        if 'salva_esci' in self.request.POST:
            return reverse_lazy('autorizzazioni:autorizzazioni_home')
        
        pk_autorizzazione=self.object.pk
        return reverse_lazy('autorizzazioni:modifica_autorizzazione', kwargs={'pk':pk_autorizzazione})
    
    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_initial(self):
        created_by = self.request.user
        return {
            'created_by': created_by,
        }

class AutorizzazioneUpdateView(LoginRequiredMixin, UpdateView):
    model = Autorizzazione
    form_class = AutorizzazioneModelForm
    template_name = 'autorizzazioni/autorizzazione.html'
    success_message = 'Autorizzazione modificata correttamente!'
        
    def get_success_url(self):        
        if 'salva_esci' in self.request.POST:
            return reverse_lazy('autorizzazioni:autorizzazioni_home')
        
        pk_autorizzazione=self.object.pk
        return reverse_lazy('autorizzazioni:modifica_autorizzazione', kwargs={'pk':pk_autorizzazione})
    

    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        pk_autorizzazione = self.object.pk        
        context['elenco_dettaglio_scadenze'] = DettaglioScadenzaAutorizzazione.objects.filter(fk_autorizzazione=pk_autorizzazione)          

        return context



def delete_autorizzazione(request, pk): 
        deleteobject = get_object_or_404(Autorizzazione, pk = pk)                 
        deleteobject.delete()
        url_match = reverse_lazy('autorizzazioni:autorizzazioni_home')
        return redirect(url_match)


class DettaglioScadenzaAutorizzazioneCreateView(LoginRequiredMixin,CreateView):
    model = DettaglioScadenzaAutorizzazione
    form_class = DettaglioScadenzaAutorizzazioneModelForm
    template_name = 'autorizzazioni/dettaglio_autorizzazione.html'
    success_message = 'Dettaglio aggiunto correttamente!'
    

    def get_success_url(self):   
        fk_autorizzazione=self.object.fk_autorizzazione.pk
        return reverse_lazy('autorizzazioni:modifica_autorizzazione', kwargs={'pk':fk_autorizzazione})
    
    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_initial(self):
        created_by = self.request.user
        fk_autorizzazione = self.kwargs['fk_autorizzazione']

        return {
            'created_by': created_by,
            'fk_autorizzazione': fk_autorizzazione
        }

    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['fk_autorizzazione']       
        context['fk_autorizzazione'] = Autorizzazione.objects.get(pk=pk) 
        return context

class DettaglioScadenzaAutorizzazioneUpdateView(LoginRequiredMixin, UpdateView):
    model = DettaglioScadenzaAutorizzazione
    form_class = DettaglioScadenzaAutorizzazioneModelForm
    template_name = 'autorizzazioni/dettaglio_autorizzazione.html'
    success_message = 'Dettaglio modificato correttamente!'
    
    
    def get_success_url(self):              
        fk_autorizzazione=self.object.fk_autorizzazione.pk        
        return reverse_lazy('autorizzazioni:modifica_autorizzazione', kwargs={'pk':fk_autorizzazione})
    

    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        pk_autorizzazione = self.kwargs['fk_autorizzazione'] 
        pk_revisione = self.kwargs['pk']       
        context['fk_autorizzazione'] = Autorizzazione.objects.get(pk=pk_autorizzazione)
        return context



def delete_dettaglio_autorizzazione(request, pk): 
        deleteobject = get_object_or_404(DettaglioScadenzaAutorizzazione, pk = pk) 
        fk_autorizzazione = deleteobject.fk_autorizzazione.pk                
        deleteobject.delete()
        url_match = reverse_lazy('autorizzazioni:modifica_autorizzazione', kwargs={'pk':fk_autorizzazione,})
        return redirect(url_match)





class ParametroAutorizzazioneCreateView(LoginRequiredMixin,CreateView):
    model = ParametroAutorizzazione
    form_class = ParametroAutorizzazioneModelForm
    template_name = 'autorizzazioni/parametro.html'
    success_message = 'Parametro aggiunto correttamente!'
    

    def get_success_url(self):        
        return reverse_lazy('autorizzazioni:tabelle_generiche_autorizzazioni')
        
    
    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_initial(self):
        created_by = self.request.user
        return {
            'created_by': created_by,
        }

class ParametroAutorizzazioneUpdateView(LoginRequiredMixin, UpdateView):
    model = ParametroAutorizzazione
    form_class = ParametroAutorizzazioneModelForm
    template_name = 'autorizzazioni/parametro.html'
    success_message = 'Parametro modificato correttamente!'
        
    def get_success_url(self):        
        return reverse_lazy('autorizzazioni:tabelle_generiche_autorizzazioni')
    

    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    

def delete_parametro(request, pk): 
        deleteobject = get_object_or_404(ParametroAutorizzazione, pk = pk)                 
        deleteobject.delete()
        url_match = reverse_lazy('autorizzazioni:tabelle_generiche_autorizzazioni')
        return redirect(url_match)




class CampoApplicazioneCreateView(LoginRequiredMixin,CreateView):
    model = CampoApplicazione
    form_class = CampoApplicazioneModelForm
    template_name = 'autorizzazioni/campo_applicazione.html'
    success_message = 'Campo Applicazione aggiunto correttamente!'
    

    def get_success_url(self):        
        if 'salva_esci' in self.request.POST:
            return reverse_lazy('autorizzazioni:tabelle_generiche_autorizzazioni')
        
        pk_campo_applicazione=self.object.pk
        return reverse_lazy('autorizzazioni:modifica_campo_applicazione', kwargs={'pk':pk_campo_applicazione})
        
    
    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_initial(self):
        created_by = self.request.user
        return {
            'created_by': created_by,
        }

class CampoApplicazioneUpdateView(LoginRequiredMixin, UpdateView):
    model = CampoApplicazione
    form_class = CampoApplicazioneModelForm
    template_name = 'autorizzazioni/campo_applicazione.html'
    success_message = 'Campo applicazione modificato correttamente!'
        
    def get_success_url(self):        
        if 'salva_esci' in self.request.POST:
            return reverse_lazy('autorizzazioni:tabelle_generiche_autorizzazioni')
        
        pk_campo_applicazione=self.object.pk
        return reverse_lazy('autorizzazioni:modifica_campo_applicazione', kwargs={'pk':pk_campo_applicazione})
    

    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        pk_campoapplicazione = self.object.pk        
        context['elenco_dettaglio_limiti'] = DettaglioCampoApplicazione.objects.filter(fk_campoapplicazione=pk_campoapplicazione)          

        return context
    
    

def delete_campo_applicazione(request, pk): 

backend/autorizzazioni/templates/autorizzazioni/autorizzazione.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }} | Autorizzazione {% endblock %}

{% block sidenav %}
{% include "core/partials/_sidenav_autorizzazioni.html" %}
{% endblock %}

{% block content %}
{% include 'core/modals/delConfirm.html' %}

<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>      
        <li class="breadcrumb-item"><a href="{% url 'autorizzazioni:autorizzazioni_home' %}">Elenco Autorizzazioni</a></li>        

        {% if form.instance.id  %}
            <li class="breadcrumb-item active" aria-current="page">Modifica {{ autorizzazione.descrizione }}</li>
        {% else %}
            <li class="breadcrumb-item active" aria-current="page">Aggiungi autorizzazione</li>
        {% endif %}             
        
        
    </ol>
</nav>

    <div class="container">
        {% if form.instance.id  %}
            <h3>Modifica {{ autorizzazione.descrizione }}</h3>
        {% else %}
            <h3> Aggiungi autorizzazione</h3>
        {% endif %}
        
        
        <hr>
        
        
        
        
        <br>


        <form method="post">
            {% csrf_token %}

            
            <input type="submit" name="salva_esci" class="btn btn-success mb-2 me-1" value="Salva ed Esci">
            <input type="submit" name="salva_continua" class="btn btn-success mb-2 me-1" value="Salva e continua">
            <button type="button" class="btn btn-danger mb-2 me-1" onclick="goBack()"><i class="bi bi-arrow-counterclockwise"></i> Annulla</button>
            <div class="row mt-2">
                <div class="col-3">
                    {{ form.descrizione|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.rilasciata_da|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.n_autorizzazione|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.data_autorizzazione|as_crispy_field }}
                </div>
                
                
            </div>
            <div class="row">
                <div class="col-3">
                    {{ form.frequenza_scadenza|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.note|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.created_by.as_hidden }}
                </div>

               


            </div>
            
            

            
            
        </form>
        <hr>
        
        {% include "core/partials/_messages.html" %}

{% if form.instance.id  %}
<div class="row">
    <!-- Tabella Rinnovi -->
    <div class="col-12"> 
        <div class="row justify-content-end">
            <div class="col">
                <p><strong>Rinnovi</strong></p>
            </div>
            <div class="col text-end">
                <a href="{% url 'autorizzazioni:aggiungi_dettaglio_autorizzazione' fk_autorizzazione=autorizzazione.pk %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Rinnovo</a>
            </div>
        </div>
        <div class="row">
            <div class="table-container">
                <table class="table table-fixed-header table-bordered table-striped mt-2">
                <caption>Rinnovi</caption>
                <thead>
                    <tr>
                        <th>Numero</th>   
                        <th>Data Rinnovo</th>
                        <th>Scadenza</th>
                        <th>Rinnovata</th>
                        <th>Documento</th>
                        <th>Azione</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for scadenza in elenco_dettaglio_scadenze %}
                    <tr>        
                        
                        <td><a href="{% url 'autorizzazioni:modifica_dettaglio_autorizzazione' fk_autorizzazione=autorizzazione.pk pk=scadenza.pk%}">{{ scadenza.n_rinnovo }}</a></td>
                        <td>{{ scadenza.data_rinnovo }}</td>
                        <td>{{ scadenza.scadenza_rinnovo }}</td>
                        <td>{{ scadenza.is_rinnovata }}</td>
                            {% if scadenza.documento %}
                                <td><a href="{{ scadenza.documento.url }}" download>{{ scadenza.documento.url }}</a></td>
                            {% else %}
                                <td>Nessun documento associato</td>
                            {% endif %}
                        
                        
                        <td class="text-center"><a href="{% url 'autorizzazioni:delete_dettaglio_autorizzazione' pk=scadenza.pk%}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{scadenza.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
                    </tr>  
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div> <!-- Fine colonna Tabella Manutenzioni Ordinarie -->



</div> <!-- Fine riga tabelle -->
{% endif %}


</div><!-- Fine Container -->

   


{% endblock %}
{% block extra_scripts %}
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            setFocusOnField('id_descrizione');
        });
    </script>
{% endblock %}

backend/autorizzazioni/templates/autorizzazioni/dettaglio_autorizzazione.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }} | Dettaglio Autorizzazione {% endblock %}

{% block sidenav %}
{% include "core/partials/_sidenav_autorizzazioni.html" %}
{% endblock %}

{% block content %}


<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>      
        <li class="breadcrumb-item"><a href="{% url 'autorizzazioni:autorizzazioni_home' %}">Elenco Autorizzazioni</a></li>        
        <li class="breadcrumb-item"><a href="{% url 'autorizzazioni:modifica_autorizzazione' pk=fk_autorizzazione.pk %}">Autorizzazione {{ fk_autorizzazione }}</a></li>        

        {% if form.instance.id  %}
            <li class="breadcrumb-item active" aria-current="page">Modifica {{ dettaglioscadenzaautorizzazione.n_rinnovo }} del {{ dettaglioscadenzaautorizzazione.data_rinnovo }}</li>
        {% else %}
            <li class="breadcrumb-item active" aria-current="page">Aggiungi Rinnovo</li>
        {% endif %}             
        
        
    </ol>
</nav>

    <div class="container">
        {% if form.instance.id  %}
            <h3>Modifica {{ dettaglioscadenzaautorizzazione.n_rinnovo }} del {{ dettaglioscadenzaautorizzazione.data_rinnovo }}</h3>
        {% else %}
            <h3> Aggiungi Rinnovo</h3>
        {% endif %}
        
        
        <hr>
        
        
        
        
        <br>


        <form class="mt-3" method="POST" novalidate enctype="multipart/form-data">
            {% csrf_token %}

            
           

            <div class="row">
                <div class="col-3">
                    {{ form.n_rinnovo|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.data_rinnovo|as_crispy_field }}
                </div>
                
                <div class="col-3">
                    {{ form.scadenza_rinnovo|as_crispy_field }}
                </div>
                <div class="col-3">
                    {{ form.documento|as_crispy_field }}
                </div>
                
                
            </div>
            <div class="row">

                <div class="col-6">
                    {{ form.note|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.is_rinnovata|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.fk_autorizzazione.as_hidden }}
                </div>
                <div class="col-2">
                    {{ form.created_by|as_crispy_field }}
                </div>
                
            </div>
            
             

            
            <input type="submit" class="btn btn-success" value="Salva">
            <button type="button" class="btn btn-danger" onclick="goBack()"><i class="bi bi-arrow-counterclockwise"></i> Annulla</button>
        </form>
        <hr>
        
        
    </div>



{% endblock %}

{% block extra_scripts %}
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            setFocusOnField('id_n_rinnovo');
        });
    </script>
{% endblock %}

backend/autorizzazioni/templates/autorizzazioni/tabelle_generiche_autorizzazioni.html
{% extends 'core/base.html' %} 
{% load static %}
{% load crispy_forms_tags %} 
{% load widget_tweaks %}
{% block head_title %}{{ block.super }} - Acquisto Pelli {% endblock head_title %} 

{% block sidenav %}
{% include "core/partials/_sidenav_autorizzazioni.html" %}
{% endblock %}

{% block content %}
{% include 'core/modals/delConfirm.html' %}

<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>      
        <li class="breadcrumb-item"><a href="{% url 'autorizzazioni:autorizzazioni_home' %}">Elenco autorizzazioni</a></li>     
        <li class="breadcrumb-item active" aria-current="page">Tabelle Generiche Autorizzazioni</li>        
    </ol>

</nav>
<div class="container">
  <br>
  <h3>Tabelle Generiche Autorizzazioni</h3>
  <hr>

  {% include "core/partials/_messages.html" %}


  <div class="row">
    <div class="col-6">
      <div class="row">
        <div class="col-6">
          <h5>Parametri</h5>
          <p>Inserire i parametri richiesti dalle varie autorizzazioni. I limiti andranno inseriti nei Campi di Applicazione.</p>                  
        </div>
        <div class="col-6 text-end">
          <a href="{% url 'autorizzazioni:crea_parametro' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi parametro</a>
        </div>
      </div>
      <div class="table-container">
        <table class="table table-bordered table-striped mt-2">
          <thead>
            <tr>
              <th>Descrizione</th>            
              <th>Azione</th>
              
            </tr>
          </thead>
          <tbody>
            {% for parametro in parametri %}
            <tr>        
              
              <td><a href="{% url 'autorizzazioni:modifica_parametro' pk=parametro.pk %}">{{ parametro.descrizione }}</a></td>
              
              <td class="text-center"><a href="{% url 'autorizzazioni:delete_parametro' pk=parametro.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{parametro.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
            </tr>  
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-6">
      <div class="row">
        <div class="col-6">
          <h5>Campi di Applicazione</h5>
          <p>Inserire i Campi di Applicazione, associarli alle Autorizzazioni e inserire i parametri con i limiti.</p>                  
        </div>
        <div class="col-6 text-end">
          <a href="{% url 'autorizzazioni:crea_campo_applicazione' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi campi applicazione</a>
        </div>
      </div>
      <div class="table-container">
        <table class="table table-bordered table-striped mt-2">
          <thead>
            <tr>
              <th>Descrizione</th>            
              <th>Azione</th>
              
            </tr>
          </thead>
          <tbody>
            {% for campo_applicazione in campi_applicazione %}
            <tr>        
              
              <td><a href="{% url 'autorizzazioni:modifica_campo_applicazione' pk=campo_applicazione.pk %}">{{ campo_applicazione.descrizione }}</a></td>
              
              <td class="text-center"><a href="{% url 'autorizzazioni:delete_campo_applicazione' pk=campo_applicazione.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{campo_applicazione.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
            </tr>  
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>



  </div>
</div>

{% endblock content %}