backend/gestionerifiuti/urls.py
from django.urls import path
from .views import (gestione_rifiuti_home, tabelle_generiche,
                    MovimentoRifiutiCreateView, MovimentoRifiutiUpdateView, delete_movimento_rifiuti,
                    CodiceCERCreateView, CodiceCERUpdateView, delete_codice_cer,
                    CodiceSmaltRecCreateView, CodiceSmaltRecUpdateView, delete_codice_smaltrec,
                    performance_triennio,
                    
)

from .utils import get_descrizione_cer, get_descrizione_smaltrec

from .charts import cer_last_year


app_name="gestionerifiuti"



urlpatterns = [

    # Home
    path("", gestione_rifiuti_home, name="gestione_rifiuti_home"), 
    
    # Tabelle generiche
    path('tabelle_generiche/', tabelle_generiche, name="tabelle_generiche"),
    
    # Manage Movimenti
    path('crea_movimento_rifiuti/', MovimentoRifiutiCreateView.as_view(), name="crea_movimento_rifiuti"), 
    path('modifica_movimento_rifiuti/<int:pk>/', MovimentoRifiutiUpdateView.as_view(), name="modifica_movimento_rifiuti"), 
    path('delete_movimento_rifiuti/<int:pk>', delete_movimento_rifiuti, name="delete_movimento_rifiuti"),
    
    # Manage Codici CER
    path('crea_codice_cer/', CodiceCERCreateView.as_view(), name="crea_codice_cer"), 
    path('modifica_codice_cer/<int:pk>/', CodiceCERUpdateView.as_view(), name="modifica_codice_cer"), 
    path('delete_codice_cer/<int:pk>', delete_codice_cer, name="delete_codice_cer"),
    
    # Manage Codici Smalt/Rec
    path('crea_codice_smaltrec/', CodiceSmaltRecCreateView.as_view(), name="crea_codice_smaltrec"), 
    path('modifica_codice_smaltrec/<int:pk>/', CodiceSmaltRecUpdateView.as_view(), name="modifica_codice_smaltrec"), 
    path('delete_codice_smaltrec/<int:pk>', delete_codice_smaltrec, name="delete_codice_smaltrec"),
            
    # Utils
    path('get_descrizione_cer/', get_descrizione_cer, name='get_descrizione_cer'),
    path('get_descrizione_smaltrec/', get_descrizione_smaltrec, name='get_descrizione_smaltrec'),

    # Charts
    path('cer_last_year/', cer_last_year, name='cer_last_year'),
    
    # Stampe
    path('performance_triennio/', performance_triennio, name='performance_triennio'),

    
]

backend/lwg/urls.py
from django.urls import path
from lwg.views import (lwg_home, lwg_procedure, scadenzario_completo
                                    )

app_name="lwg"

urlpatterns = [
    
    # Home LWG
    path('', lwg_home, name='lwg_home'),
    
    #LWG Procedure    
    path('lwg_procedure/<int:fk_lwgsection>', lwg_procedure, name='lwg_procedure'),

    # Scadenzario    
    path('scadenzario_completo/', scadenzario_completo, name='scadenzario_completo'),    

    
]

backend/qmsproject/urls.py
from core.views import home
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("", home, name="home"),
    path("core/", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("anagrafiche/", include("anagrafiche.urls")),
    path("human_resources/", include("human_resources.urls")),
    path("acquistopelli/", include("acquistopelli.urls")),
    path("articoli/", include("articoli.urls")),
    path("manualeprocedure/", include("manualeprocedure.urls")),
    path("monitoraggi/", include("monitoraggi.urls")),
    path("manutenzioni/", include("manutenzioni.urls")),
    path("lwg/", include("lwg.urls")),
    path("autorizzazioni/", include("autorizzazioni.urls")),
    path("gestionerifiuti/", include("gestionerifiuti.urls")),
    path("nonconformity/", include("nonconformity.urls")),
    path("chem_man/", include("chem_man.urls")),
    path("antincendio/", include("antincendio.urls")),
    path("ricette/", include("ricette.urls")),
    path("air_emissions/", include("air_emissions.urls")),
    path("vendite/", include("vendite.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    # API
    path("api/accounts/", include("accounts.urls")),
    path("api/anagrafiche/", include("anagrafiche.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/gestionerifiuti/models.py
from django.db import models
from django.contrib.auth.models import User


class CodiceCER(models.Model):
    codice = models.CharField(max_length=7, null=False, blank=False)
    descrizione = models.CharField(max_length=300, null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(User, related_name='codice_cer', null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.codice
    


class CodiceSmaltRec(models.Model):

    # Smaltimento o Recupero
    SMALTIMENTO = 'smaltimento'
    RECUPERO = 'recupero'
    
    
    CHOICES_SMALT_REC = (
        (SMALTIMENTO, 'Smaltimento'),
        (RECUPERO, 'Recupero'),        
    )
    codice = models.CharField(max_length=4, null=False, blank=False)
    descrizione = models.CharField(max_length=200, null=True, blank=True)
    smalt_rec =  models.CharField(max_length=15, choices=CHOICES_SMALT_REC)
    note = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(User, related_name='codice_smalt_rec', null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.codice
    

class MovimentoRifiuti(models.Model):

    # Carico o Scarico
    CARICO = 'carico'
    SCARICO = 'scarico'
    
    
    CHOICES_CAR_SCAR = (
        (CARICO, 'Carico'),
        (SCARICO, 'Scarico'),        
    )

    data_movimento = models.DateField()
    fk_codicecer = models.ForeignKey(CodiceCER, on_delete=models.CASCADE, related_name='movimento_rifiuti')
    car_scar =  models.CharField(max_length=7, choices=CHOICES_CAR_SCAR)
    quantity = models.DecimalField(max_digits=10, decimal_places=2)
    fk_smaltrec = models.ForeignKey(CodiceSmaltRec, on_delete=models.CASCADE, related_name='movimento_rifiuti', null=True, blank=True)
    note = models.TextField(null=True, blank=True)
    created_by = models.ForeignKey(User, related_name='movimento_rifiuti', null=True, blank=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-data_movimento"]
        verbose_name_plural = "Movimenti Rifiuti"

    def __str__(self):
        return str(self.data_movimento)

backend/gestionerifiuti/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.db.models import Q, Sum, DecimalField

from datetime import date, timedelta, datetime


from .models import (CodiceCER, 
                    CodiceSmaltRec, 
                    MovimentoRifiuti,
                    )
from .filters import MovimentoRifiutiFilter

from .forms import (MovimentoRifiutiModelForm,
                    CodiceCERModelForm,
                    CodiceSmaltRecModelForm
                    
                    )


from .utils import somma_quantita_per_anno_smaltimento_recupero

def gestione_rifiuti_home(request): 

    movimenti_rifiuti = MovimentoRifiuti.objects.all()
    
    movimenti_rifiuti_filter = MovimentoRifiutiFilter(request.GET, queryset=movimenti_rifiuti)
    
    current_date = date.today()
    begin_date = current_date - timedelta(days=365)
    
    
    movimenti_recupero = MovimentoRifiuti.objects.filter(Q(**{f"data_movimento__lte": current_date}) & Q(**{f"data_movimento__gte": begin_date})).filter(car_scar="carico").filter(fk_smaltrec__smalt_rec="recupero").aggregate(total=Sum('quantity'))['total']
    movimenti_smaltimento = MovimentoRifiuti.objects.filter(Q(**{f"data_movimento__lte": current_date}) & Q(**{f"data_movimento__gte": begin_date})).filter(car_scar="carico").filter(fk_smaltrec__smalt_rec="smaltimento").aggregate(total=Sum('quantity'))['total']


    if movimenti_recupero is not None and movimenti_smaltimento is not None:
        tot_movimenti = movimenti_recupero + movimenti_smaltimento
    else:    
        tot_movimenti = None

    

    if tot_movimenti is not None and tot_movimenti != 0:
        perc_recupero = round((movimenti_recupero * 100) / tot_movimenti, 2)
    else:
        # Gestisci il caso in cui tot_movimenti è zero o None
        perc_recupero = 0
    
    if tot_movimenti is not None and tot_movimenti != 0:
        perc_smaltimento = round((movimenti_smaltimento * 100) / tot_movimenti, 2)
    else:
        # Gestisci il caso in cui tot_movimenti è zero o None
        perc_smaltimento = 0


    print(f'movimenti_recupero: {movimenti_recupero}')
    print(f'movimenti_smaltimento: {movimenti_smaltimento}')
    
    
    
    page = request.GET.get('page', 1)
    paginator = Paginator(movimenti_rifiuti_filter.qs, 50)  # Utilizza lotti_filter.qs per la paginazione
    
        
    try:
        movimenti_rifiuti_paginator = paginator.page(page)
    except PageNotAnInteger:
        movimenti_rifiuti_paginator = paginator.page(1)
    except EmptyPage:
        movimenti_rifiuti_paginator = paginator.page(paginator.num_pages)
        
    context = {
        'dati_paginator': movimenti_rifiuti_paginator,
        'filter': movimenti_rifiuti_filter,
        'movimenti_recupero': movimenti_recupero,
        'movimenti_smaltimento': movimenti_smaltimento,
        'perc_recupero': perc_recupero,
        'perc_smaltimento': perc_smaltimento

        
    }
    
    return render(request, 'gestionerifiuti/gestione_rifiuti_home.html', context)




def tabelle_generiche(request):
    codici_cer = CodiceCER.objects.all()
    codici_smaltrec = CodiceSmaltRec.objects.all()

    context = {'codici_cer': codici_cer, 
               'codici_smaltrec': codici_smaltrec,                           
                }
    
    return render(request, "gestionerifiuti/tabelle_generiche.html", context)



class MovimentoRifiutiCreateView(LoginRequiredMixin,CreateView):
    model = MovimentoRifiuti
    form_class = MovimentoRifiutiModelForm
    template_name = 'gestionerifiuti/movimento_rifiuti.html'
    success_message = 'Carico/scarico aggiunto correttamente!'
    

    def get_success_url(self):
        
        return reverse_lazy('gestionerifiuti:gestione_rifiuti_home')
    
    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_initial(self):
        created_by = self.request.user
        return {
            'created_by': created_by,
        }

class MovimentoRifiutiUpdateView(LoginRequiredMixin, UpdateView):
    model = MovimentoRifiuti
    form_class = MovimentoRifiutiModelForm
    template_name = 'gestionerifiuti/movimento_rifiuti.html'
    success_message = 'Carico/scarico modificato correttamente!'
    
    
    def get_success_url(self):        
        
        return reverse_lazy('gestionerifiuti:gestione_rifiuti_home')
    

    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        # pk_procedura = self.object.pk        
        # context['elenco_revisioni'] = RevisioneProcedura.objects.filter(fk_procedura=pk_procedura) 
        # context['elenco_moduli'] = Modulo.objects.filter(fk_procedura=pk_procedura) 

        return context


def delete_movimento_rifiuti(request, pk): 
        deleteobject = get_object_or_404(MovimentoRifiuti, pk = pk)                 
        deleteobject.delete()
        url_match = reverse_lazy('gestionerifiuti:gestione_rifiuti_home')
        return redirect(url_match)
    

# Crea, modifica, cancella Codice CER
class CodiceCERCreateView(LoginRequiredMixin,CreateView):
    model = CodiceCER
    form_class = CodiceCERModelForm
    template_name = 'gestionerifiuti/codice_cer.html'
    success_message = 'Codice CER aggiunto correttamente!'
    

    def get_success_url(self):        
        return reverse_lazy('gestionerifiuti:tabelle_generiche')
    
    
    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_initial(self):
        created_by = self.request.user
        return {
            'created_by': created_by,
        }



class CodiceCERUpdateView(LoginRequiredMixin, UpdateView):
    model = CodiceCER
    form_class = CodiceCERModelForm
    template_name = 'gestionerifiuti/codice_cer.html'
    success_message = 'Codice CER modificato correttamente!'
    
    
    def get_success_url(self):        
        
        return reverse_lazy('gestionerifiuti:tabelle_generiche')
    

    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        # pk_procedura = self.object.pk        
        # context['elenco_revisioni'] = RevisioneProcedura.objects.filter(fk_procedura=pk_procedura) 
        # context['elenco_moduli'] = Modulo.objects.filter(fk_procedura=pk_procedura) 

        return context


def delete_codice_cer(request, pk): 
        deleteobject = get_object_or_404(CodiceCER, pk = pk)                 
        deleteobject.delete()
        url_match = reverse_lazy('gestionerifiuti:tabelle_generiche')
        return redirect(url_match)
    



# Crea, modifica, cancella Codice Smalt/Rec

class CodiceSmaltRecCreateView(LoginRequiredMixin,CreateView):
    model = CodiceSmaltRec
    form_class = CodiceSmaltRecModelForm
    template_name = 'gestionerifiuti/codice_smaltrec.html'
    success_message = 'Codice Smalt/Rec aggiunto correttamente!'
    

    def get_success_url(self):        
        return reverse_lazy('gestionerifiuti:tabelle_generiche')
    
    
    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_initial(self):
        created_by = self.request.user
        return {
            'created_by': created_by,
        }
        
        
        
class CodiceSmaltRecUpdateView(LoginRequiredMixin, UpdateView):
    model = CodiceSmaltRec
    form_class = CodiceSmaltRecModelForm
    template_name = 'gestionerifiuti/codice_smaltrec.html'
    success_message = 'Codice Smalt/Rec modificato correttamente!'
    
    
    def get_success_url(self):        
        
        return reverse_lazy('gestionerifiuti:tabelle_generiche')
    

    def form_valid(self, form):        
        messages.info(self.request, self.success_message) # Compare sul success_url
        return super().form_valid(form)
    
    def get_context_data(self, **kwargs):        
        context = super().get_context_data(**kwargs)
        # pk_procedura = self.object.pk        
        # context['elenco_revisioni'] = RevisioneProcedura.objects.filter(fk_procedura=pk_procedura) 
        # context['elenco_moduli'] = Modulo.objects.filter(fk_procedura=pk_procedura) 

        return context


def delete_codice_smaltrec(request, pk): 
        deleteobject = get_object_or_404(CodiceSmaltRec, pk = pk)                 
        deleteobject.delete()
        url_match = reverse_lazy('gestionerifiuti:tabelle_generiche')
        return redirect(url_match)
    
    
# Stampe
def performance_triennio(request):
    risultato_smaltimento = somma_quantita_per_anno_smaltimento_recupero('smaltimento')
    risultato_recupero = somma_quantita_per_anno_smaltimento_recupero('recupero')

    # Trova gli anni dall'unione dei dati di smaltimento e recupero
    anni_smaltimento = set()
    for dati_per_anno in risultato_smaltimento.values():
        anni_smaltimento.update(dati_per_anno.keys())

    anni_recupero = set()
    for dati_per_anno in risultato_recupero.values():
        anni_recupero.update(dati_per_anno.keys())

    anni = sorted(anni_smaltimento.union(anni_recupero))

backend/gestionerifiuti/templates/gestionerifiuti/gestione_rifiuti_home.html
{% extends 'core/base.html' %} 
{% load static %}
{% load crispy_forms_tags %} 
{% load widget_tweaks %}
{% load custom_filters %}
{% block head_title %}{{ block.super }} - Gestione Rifiuti {% endblock head_title %} 

{% block sidenav %}
{% include "core/partials/_sidenav_gestione_rifiuti.html" %}
{% endblock %}



{% block content %}

<nav aria-label="breadcrumb" class="mt-3">
  <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>      
      <li class="breadcrumb-item active" aria-current="page">Movimenti Rifiuti</li>
  </ol>
</nav>
{% include 'core/modals/delConfirm.html' %}


<div class="container">
<div class="row">
  <div class="col-4">
  <h5>Destinazione Rifiuti Prodotti ultimo anno:</h5>
    {% if movimenti_recupero %}
      <h6>Recupero kg.: {{ movimenti_recupero|format_number_dec_thousand }} ({{ perc_recupero }}%)</h6>
    {% else %}
      <h6>Nessun rifiuto a recupero</h6>
    {% endif %}
    {% if movimenti_smaltimento %}
      <h6>Smaltimento kg.: {{ movimenti_smaltimento|format_number_dec_thousand }} ({{ perc_smaltimento }}%)</h6>
    {% else %}
      <h6>Nessun rifiuto a smaltimento</h6>
    {% endif %}
  </div>

  <div class="col-4">        
    <canvas id="cer_last_year" data-url="{% url 'gestionerifiuti:cer_last_year' %}"></canvas>
  </div>


</div>

  <br>
  <h3>Lista Movimenti Rifiuti</h3>
  <hr>
  

 


  <!-- filtro -->
  <div class="row">
    <div class="col">
        <div class="card card-body">
            <form method="get">

                <div class="table-responsive-sm">
                    <table class="table table-hover table-striped table-bordered">
                        <thead class="thead-dark">
                            <tr>     
                                <th>Data Movimento</th>
                                <th>Codice Cer</th>                                    
                                <th>Carico/Scarico</th>                                    
                                <th>Smalt/Rec</th>                                    
                                

                            </tr>
                        </thead>                            
                        <tbody>
                            <tr>                                    
                                <td style="width: 20%">{{ filter.form.data_movimento|as_crispy_field }}</td>                                    
                                <td style="width: 20%">{{ filter.form.fk_codicecer|as_crispy_field }}</td>                                
                                <td style="width: 20%">{{ filter.form.car_scar|as_crispy_field }}</td>                                
                                <td style="width: 20%">{{ filter.form.fk_smaltrec|as_crispy_field }}</td>                                
                                
                            </tr>
                        </tbody>
                    </table>
                </div>
                <button class="btn btn-primary" type="submit">Cerca</button>
                <a class="btn btn-success" href="{% url 'gestionerifiuti:gestione_rifiuti_home' %}"><i class="bi bi-arrow-counterclockwise"></i>&nbsp;&nbsp; Pulisci campi</a>
            </form>        
        </div>
    </div>        
</div>
<!-- fine filtro-->
  <hr>
  {% include "core/partials/_messages.html" %}
  <br>
  

  <a class="btn btn-sm btn-success mt-2 mb-4" id="id_aggiungi" href="{% url 'gestionerifiuti:crea_movimento_rifiuti' %}"><span class="bi bi-person-plus-fill"></span> Aggiungi</a>
  <br>
    <table class="table table-bordered table-striped">
        <thead>
          <tr>
            
            <th>Data Movimento</th>
            <th>Codice Cer</th>                                    
            <th>Carico/Scarico</th>                                    
            <th>Smalt/Rec</th>  
            <th>Quantità</th>  
            <th>Azione</th>  


            
          </tr>
        </thead>
        <tbody>
          {% for movimento in dati_paginator %}
          <tr>        
            
            
            <td><a href="{% url 'gestionerifiuti:modifica_movimento_rifiuti' pk=movimento.pk %}">{{ movimento.data_movimento|date:'d/m/Y' }}</a></td>
            
            <td>{{ movimento.fk_codicecer.codice }}</td>
            <td>{{ movimento.car_scar }}</td>
            <td>{{ movimento.fk_smaltrec.codice }}</td>
            {% if movimento.car_scar == 'carico' %}
              <td class="text-end">{{ movimento.quantity|format_number_dec_thousand }}</td>
            {% else %}
              <td class="text-end text-danger">{{ movimento.quantity|format_number_dec_thousand }}</td>
            {% endif %}

            <td class="text-center"><a href="{% url 'gestionerifiuti:delete_movimento_rifiuti' pk=movimento.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{movimento.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
            
          </tr>  
          {% endfor %}
        </tbody>
      </table>
      <!-- Pagination -->
{% if dati_paginator.has_other_pages %}
<nav>
  <ul class="pagination justify-content-center">
    {% if dati_paginator.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ dati_paginator.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link" aria-hidden="true">&laquo;</span>
      </li>
    {% endif %}

    {% for page in dati_paginator.paginator.page_range %}
      {% if page == dati_paginator.number %}
        <li class="page-item active">
          <span class="page-link">{{ page }}</span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page }}">{{ page }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if dati_paginator.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ dati_paginator.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <span class="page-link" aria-hidden="true">&raquo;</span>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}
<!-- End Pagination -->

</div>



{% endblock content %}

{% block extra_scripts %}

<script>



  $(function () {
  
  var $cer_last_year = $("#cer_last_year");
  $.ajax({
    url: $cer_last_year.data("url"),
    success: function (data) {
  
      var ctx = $cer_last_year[0].getContext("2d");        
      new Chart(ctx, {
        type: 'bar',
        data: {
          labels: data.labels,
          datasets: [{
            label: 'CER Ultimi 12 mesi',
            backgroundColor: getRandomColor(),
            data: data.data
          }]          
        },
        options: {
          responsive: true,
          legend: {
            position: 'top',
          },
          title: {
            display: true,
            text: 'CER Ultimi 12 mesi'
          },
          
        }
      });
  
    }
  });
  
  });
  document.addEventListener("DOMContentLoaded", function() {
        setFocusOnField('id_aggiungi');
  });
</script>

{% endblock %}

backend/gestionerifiuti/templates/gestionerifiuti/tabelle_generiche.html
{% extends 'core/base.html' %} 
{% load static %}
{% load crispy_forms_tags %} 
{% load widget_tweaks %}
{% block head_title %}{{ block.super }} - Acquisto Pelli {% endblock head_title %} 

{% block sidenav %}
{% include "core/partials/_sidenav_gestione_rifiuti.html" %}
{% endblock %}

{% block content %}
{% include 'core/modals/delConfirm.html' %}

<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>      
        <li class="breadcrumb-item"><a href="{% url 'gestionerifiuti:gestione_rifiuti_home' %}">Lista Movimenti Rifiuti</a></li>     
        <li class="breadcrumb-item active" aria-current="page">Tabelle Generiche</li>        
    </ol>

</nav>
<div class="container">
  <h3> Tabelle Generiche Gestione Rifiuti</h3>
  <hr>

  {% include "core/partials/_messages.html" %}


  <div class="row">
    <div class="col-6">
      <div class="row">
        <div class="col-6">
          <h5>Codici CER</h5>
          <p>Elenco dei codici CER</p>                  
        </div>
        <div class="col-6 text-end">
          <a href="{% url 'gestionerifiuti:crea_codice_cer' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Codice CER</a>
        </div>
      </div>
      <div class="table-container">
        <table class="table table-bordered table-striped mt-2">
          <thead>
            <tr>
              <th>Codice</th>            
              <th>Descrizione</th>            
              <th>Azione</th>
              
            </tr>
          </thead>
          <tbody>
            {% for codice_cer in codici_cer %}
            <tr>        
              
              <td><a href="{% url 'gestionerifiuti:modifica_codice_cer' pk=codice_cer.pk %}">{{ codice_cer.codice }}</a></td>
              <td>{{ codice_cer.descrizione }}</td>
              
              <td class="text-center"><a href="{% url 'gestionerifiuti:delete_codice_cer' pk=codice_cer.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{codice_cer.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
            </tr>  
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>

    <div class="col-6">
      <div class="row">
        <div class="col-6">
          <h5>Codici Smaltimento/Recupero</h5>
          <p>Inserire i codici di Smaltimento/Recupero.</p>                  
        </div>
        <div class="col-6 text-end">
          <a href="{% url 'gestionerifiuti:crea_codice_smaltrec' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi codice Smalt/Rec</a>
        </div>
      </div>
      <div class="table-container">
        <table class="table table-bordered table-striped mt-2">
          <thead>
            <tr>
              <th>Codice</th>            
              <th>Descrizione</th>            
              <th>Azione</th>
              
            </tr>
          </thead>
          <tbody>
            {% for codice_smaltrec in codici_smaltrec %}
            <tr>        
              
              <td><a href="{% url 'gestionerifiuti:modifica_codice_smaltrec' pk=codice_smaltrec.pk %}">{{ codice_smaltrec.codice }}</a></td>
              <td>{{ codice_smaltrec.descrizione }}</td>
              <td class="text-center"><a href="{% url 'gestionerifiuti:delete_codice_smaltrec' pk=codice_smaltrec.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{codice_smaltrec.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
            </tr>  
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>



  </div>
</div>

{% endblock content %}