backend/human_resources/urls.py
from django.urls import path

from .charts import (age_groups, num_tot_dipendenti,
                     num_tot_dipendenti_assunti_anno,
                     num_tot_dipendenti_dimessi_anno,
                     num_tot_dipendenti_orario, num_tot_dipendenti_plot,
                     operatori_per_reparto, ore_formazione)
from .report_lab import *
from .reports import *
from .views import *

app_name = 'human_resources'

urlpatterns = [
    
    # Tabelle generiche
    path('tabelle_generiche/', tabelle_generiche, name="tabelle_generiche"),  
    path('tabelle_generiche_formazione/', tabelle_generiche_formazione, name="tabelle_generiche_formazione"),  
    
    # Human Resources
    path('', human_resources_home, name="human_resources"),
    path('update_human_resource/<int:pk>/', HRUpdateView.as_view(), name="update_human_resource"),
    path('create_human_resource/', HumanResourceCreateView.as_view(), name="create_human_resource"), 
    
    # Dashboard formazione 
    path('dashboard_formazione/', dashboard_formazione, name="dashboard_formazione"), 
    
    # Dashboard registro ore
    path('dashboard_registro_ore/', dashboard_registro_ore, name="dashboard_registro_ore"), 
    path('crea_registro_ore/', RegistroOreLavoroCreateView.as_view(), name="crea_registro_ore"), 
    path('modifica_registro_ore/<int:pk>/', RegistroOreLavoroUpdateView.as_view(), name="modifica_registro_ore"), 
    path('delete_registro_ore/<int:pk>', delete_registro_ore, name="delete_registro_ore"),
    
    # Charts
    path('ore_formazione/', ore_formazione, name='ore_formazione'),
    path('hr_count/', operatori_per_reparto, name='hr_count'),
    path('age_groups/', age_groups, name='age_groups'),
    path('num_tot_dipendenti/', num_tot_dipendenti, name='num_tot_dipendenti'),
    path('num_tot_dipendenti_plot/', num_tot_dipendenti_plot, name='num_tot_dipendenti_plot'),
    path('num_tot_dipendenti_orario/', num_tot_dipendenti_orario, name='num_tot_dipendenti_orario'),
    path('num_tot_dipendenti_assunti_anno/', num_tot_dipendenti_assunti_anno, name='num_tot_dipendenti_assunti_anno'),
    path('num_tot_dipendenti_dimessi_anno/', num_tot_dipendenti_dimessi_anno, name='num_tot_dipendenti_dimessi_anno'),
    
    
    


    # Centro di Lavoro 
    path('crea_centro_di_lavoro/', CentrodiLavoroCreateView.as_view(), name="crea_centro_di_lavoro"),  
    path('modifica_centro_di_lavoro/<int:pk>', CentrodiLavoroUpdateView.as_view(), name="modifica_centro_di_lavoro"),  
    path('delete_centro_di_lavoro/<int:pk>', delete_centro_di_lavoro, name="delete_centro_di_lavoro"),

    # Ward 
    path('create_ward/', WardCreateView.as_view(), name="create_ward"),  
    path('update_ward/<int:pk>', WardUpdateView.as_view(), name="update_ward"),  
    path('delete_ward/<int:pk>', delete_ward, name="delete_ward"),  

    # Role
    path('create_role/', RoleCreateView.as_view(), name="create_role"),  
    path('update_role/<int:pk>', RoleUpdateView.as_view(), name="update_role"),  
    path('delete_role/<int:pk>', delete_role, name="delete_role"),

    # Safety Role
    path('create_safety_role/', Safety_RoleCreateView.as_view(), name="create_safety_role"),  
    path('update_safety_role/<int:pk>', Safety_RoleUpdateView.as_view(), name="update_safety_role"),  
    path('delete_safety_role/<int:pk>', delete_safety_role, name="delete_safety_role"),
    
    # Area Formazione
    path('crea_area_formazione/', AreaFormazioneCreateView.as_view(), name="crea_area_formazione"),  
    path('modifica_area_formazione/<int:pk>', AreaFormazioneUpdateView.as_view(), name="modifica_area_formazione"),  
    path('delete_area_formazione/<int:pk>', delete_area_formazione, name="delete_area_formazione"),
    
    # Corso Formazione
    path('crea_corso_formazione/', CorsoFormazioneCreateView.as_view(), name="crea_corso_formazione"),  
    path('modifica_corso_formazione/<int:pk>', CorsoFormazioneUpdateView.as_view(), name="modifica_corso_formazione"),  
    path('delete_corso_formazione/<int:pk>', delete_corso_formazione, name="delete_corso_formazione"),
    
    # Registro Formazione
    path('crea_registro_formazione/', RegistroFormazioneCreateView.as_view(), name="crea_registro_formazione"),  
    path('modifica_registro_formazione/<int:pk>', RegistroFormazioneUpdateView.as_view(), name="modifica_registro_formazione"),  
    path('delete_registro_formazione/<int:pk>', delete_registro_formazione, name="delete_registro_formazione"),
    
    # Dettaglio Registro Formazione
    path('<int:pk>/crea_dettaglio_registro_formazione/', DettaglioRegistroFormazioneCreateView.as_view(), name="crea_dettaglio_registro_formazione"),  
    path('<int:fk_registro_formazione>/modifica_dettaglio_registro_formazione/<int:pk>/', DettaglioRegistroFormazioneUpdateView.as_view(), name="modifica_dettaglio_registro_formazione"),  
    path('delete_dettaglio_registro_formazione/<int:pk>', delete_dettaglio_registro_formazione, name="delete_dettaglio_registro_formazione"),
    #path('<int:fk_attrezzatura>/modifica_manutenzione_straordinaria/<int:pk>/', ManutenzioneStraordinariaUpdateView.as_view(), name="modifica_manutenzione_straordinaria"), 

    # Valutazione operatori
    path('<int:pk>/crea_valutazione_operatore/', ValutazioneOperatoreCreateView.as_view(), name="crea_valutazione_operatore"),  
    path('<int:pk>/modifica_valutazione_operatore/<int:id>', ValutazioneOperatoreUpdateView.as_view(), name="modifica_valutazione_operatore"),  
    path('delete_valutazione_operatore/<int:pk>', delete_valutazione_operatore, name="delete_valutazione_operatore"),

    # XR Safety_roles-Operatori
    path('<int:pk>/crea_hr_safety/', HR_SafetyCreateView.as_view(), name="crea_hr_safety"),
    path('<int:pk>/modifica_hr_safety/', HR_SafetyUpdateView.as_view(), name="modifica_hr_safety"),  
    path('delete_hr_safety/<int:pk>', delete_hr_safety, name="delete_hr_safety"),
    
    # Stampe
    path('stampa_risorse_umane/', stampa_risorse_umane, name="stampa_risorse_umane"), 
    path('performance_triennio/', performance_triennio, name="performance_triennio"),     
    path('report/performance_chart/', generate_chart_report, name='performance_report_chart'),

    # Scadenzario
    path('scadenzario/', scadenzario, name="scadenzario"), 
    path('scadenze_formazione/', scadenze_formazione, name="scadenze_formazione"), 

    
]

backend/lwg/urls.py
from django.urls import path
from lwg.views import (lwg_home, lwg_procedure, scadenzario_completo
                                    )

app_name="lwg"

urlpatterns = [
    
    # Home LWG
    path('', lwg_home, name='lwg_home'),
    
    #LWG Procedure    
    path('lwg_procedure/<int:fk_lwgsection>', lwg_procedure, name='lwg_procedure'),

    # Scadenzario    
    path('scadenzario_completo/', scadenzario_completo, name='scadenzario_completo'),    

    
]

backend/qmsproject/urls.py
from core.views import home
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("", home, name="home"),
    path("core/", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("anagrafiche/", include("anagrafiche.urls")),
    path("human_resources/", include("human_resources.urls")),
    path("acquistopelli/", include("acquistopelli.urls")),
    path("articoli/", include("articoli.urls")),
    path("manualeprocedure/", include("manualeprocedure.urls")),
    path("monitoraggi/", include("monitoraggi.urls")),
    path("manutenzioni/", include("manutenzioni.urls")),
    path("lwg/", include("lwg.urls")),
    path("autorizzazioni/", include("autorizzazioni.urls")),
    path("gestionerifiuti/", include("gestionerifiuti.urls")),
    path("nonconformity/", include("nonconformity.urls")),
    path("chem_man/", include("chem_man.urls")),
    path("antincendio/", include("antincendio.urls")),
    path("ricette/", include("ricette.urls")),
    path("air_emissions/", include("air_emissions.urls")),
    path("vendite/", include("vendite.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    # API
    path("api/accounts/", include("accounts.urls")),
    path("api/anagrafiche/", include("anagrafiche.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/human_resources/templates/human_resources/safety_role.html
{% extends 'core/base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ block.super }} | Generiche - Centro di Lavoro {% endblock %}

{% block sidenav %}
{% include "core/partials/_sidenav_human_resources.html" %}
{% endblock %}

{% block content %}


<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>      
        <li class="breadcrumb-item"><a href="{% url 'human_resources:human_resources' %}">Operatori</a></li>        
        <li class="breadcrumb-item"><a href="{% url 'human_resources:tabelle_generiche' %}">Tabelle Generiche</a></li>     

        {% if form.instance.id  %}
            <li class="breadcrumb-item active" aria-current="page">Modifica {{ safety_role.descrizione }}</li>
        {% else %}
            <li class="breadcrumb-item active" aria-current="page">Aggiungi Incarico Sicurezza</li>
        {% endif %}             
        
        
    </ol>
</nav>

    <div class="container">
        {% if form.instance.id  %}
            <h3>Modifica {{ safety_role.descrizione }}</h3>
        {% else %}
            <h3> Aggiungi Incarico Sicurezza</h3>
        {% endif %}
        
        
        <hr>
        
        
        
        
        <br>


        <form method="post">
            {% csrf_token %}

            

            <div class="row">
                <div class="col-5">
                    {{ form.descrizione|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.note|as_crispy_field }}
                </div>
                <div class="col-1">
                    {{ form.created_by|as_crispy_field }}
                </div>
                
                
            </div>
            
            

            
            <input type="submit" class="btn btn-success mb-2 me-1" value="Salva">
            <button type="button" class="btn btn-danger mb-2 me-1" onclick="cancelAndRedirectTo('{% url 'human_resources:tabelle_generiche' %}')"><i class="bi bi-arrow-counterclockwise"></i> Annulla</button>
        </form>
        <hr>
        
        
    </div>



{% endblock %}

{% block extra_scripts %}
<script>
document.addEventListener("DOMContentLoaded", function() {
            setFocusOnField('id_descrizione');
        });

    
</script>

{% endblock %} 

backend/human_resources/templates/human_resources/single_operator.html
{% extends 'core/base.html' %} 
{% load static %}
{% load crispy_forms_tags %} 
{% load widget_tweaks %}
{% block head_title %}{{ block.super }} - Operatore{% endblock head_title %} 

{% block sidenav %}
{% include "core/partials/_sidenav_human_resources.html" %}
{% endblock %}

{% block content %}
{% include 'core/modals/delConfirm.html' %}

<div class="container">
    <br>
    <nav aria-label="breadcrumb" class="mt-3">
      <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>      
          <li class="breadcrumb-item"><a href="{% url 'human_resources:human_resources' %}">Risorse Umane</a></li>        
  
          {% if form.instance.id  %}
              <li class="breadcrumb-item active" aria-current="page">{{ humanresource.cognomedipendente }} {{ humanresource.nomedipendente }}</li>
          {% else %}
              <li class="breadcrumb-item active" aria-current="page">Aggiungi operatore</li>
          {% endif %}             
          
          
      </ol>
  </nav>
    
    <hr>
    {% include "core/partials/_messages.html" %}
    <!-- Form nuovo operatore -->
    {% if immagine %}
      <img src="{{ object.immagine.url }}" 
        alt="{{ object.cognomedipendente }}" 
        style="height: auto; width: 200px; border-radius: 50%; margin-top: 25px;" 
        class="avatar"  
        accept=".jpg,.jpeg,.png"
        id="preview-image"
        />
    {% else %}
      <p>Nessuna immagine</p>
    {% endif %}
    <hr>

    


    <ul class="nav nav-tabs" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home-tab-pane" type="button" role="tab" aria-controls="home-tab-pane" aria-selected="true">Generalità</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#formazione-tab-pane" type="button" role="tab" aria-controls="profile-tab-pane" aria-selected="false">Formazione</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="valutazione-tab" data-bs-toggle="tab" data-bs-target="#valutazione-tab-pane" type="button" role="tab" aria-controls="valutazione-tab-pane" aria-selected="false">Valutazione</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="incarichi-tab" data-bs-toggle="tab" data-bs-target="#incarichi-tab-pane" type="button" role="tab" aria-controls="incarichi-tab-pane" aria-selected="false">Altri Incarichi</button>
      </li>
      
    </ul>

    

    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="home-tab-pane" role="tabpanel" aria-labelledby="home-tab" tabindex="0">
        
        <div class="form-group mt-3">
          <form class="mt-3" method="POST" novalidate enctype="multipart/form-data">
              {% csrf_token %}
              
              <input type="submit" name="salva_esci" class="btn btn-success mb-2 me-1" value="Salva ed Esci">
              <input type="submit" name="salva_continua" class="btn btn-success mb-2 me-1" value="Salva e Continua">
          
                  <div class="row mb-4 mt-3">
                    
                    <div class="col-md-12 border rounded shadow-sm">
                      <div class="row mt-3">
                          <div class = "col-md-3">
                            {{ form.immagine|as_crispy_field }}
                          </div>
                          
                          <div class="col-md-3">
                            {{ form.cognomedipendente|as_crispy_field }}
                          </div>
                          <div class="col-md-3">
                            {{ form.nomedipendente|as_crispy_field }} 
                          </div> 
                          
                          <div class="col-md-2">
                            {{ form.gender|as_crispy_field }}
                          </div>    
                      </div>
                      <div class="row"> 
                        <div class="col-3">
                          {{ form.data_nascita|as_crispy_field }}
                      </div>                         
                        <div class="col-3">
                          {{ form.country|as_crispy_field }}
                      </div>
                          <div class="col-md-3">
                            {{ form.dataassunzione|as_crispy_field }}
                          </div>
                          <div class="col-md-3">
                            {{ form.datadimissioni|as_crispy_field }} 
                          </div>     
                      </div>
                      <hr>
                      <div class="row"> 
                        <div class="col-3">
                          {{ form.contratto|as_crispy_field }}
                      </div>                         
                        <div class="col-3">
                          {{ form.orario|as_crispy_field }}
                      </div>                           
                      </div>
                      <hr>


                      <div class="row mt-4">                          
                          
                          <div class="col-md-5">
                            {{ form.fk_mansione|as_crispy_field }}
                          </div>
                          <div class="col-md-5">
                            {{ form.fk_reparto|as_crispy_field }} 
                          </div> 
                          <div class="col-md-5">
                              {{ form.qualifica|as_crispy_field }} 
                          </div>        
                      </div>
                      <div class="row">                          
                          
                          <div class="col">
                            {{ form.commenti|as_crispy_field }}
                          </div>
                            
                      </div>
                      <hr>
                      

                      

                  </div>
                    </div>

      <!-- fine form -->
      </form>
      </div>
      </div>

      <div class="tab-pane fade" id="formazione-tab-pane" role="tabpanel" aria-labelledby="formazione-tab" tabindex="0">
        <table class="table table-bordered table-striped mt-2">
          <thead>
            <tr>
              <th>Data</th>            
              <th>Corso</th>
              <th>Ore Totali</th>        
              <th>Area Formazione</th>
              <th>Prossima Scadenza</th>
              
            </tr>
          </thead>
          <tbody>
            {% for formazione in elenco_formazione %}
            <tr>        
              
              <td>{{ formazione.fk_registro_formazione.data_formazione }}</td>
              <td>{{ formazione.fk_registro_formazione.fk_corso.descrizione }}</td>
              <td>{{ formazione.fk_registro_formazione.ore }}</td>        
              <td>{{ formazione.fk_registro_formazione.fk_corso.fk_areaformazione }}</td>
              <td>{{ formazione.prossima_scadenza|default:"Nessuna Scadenza" }}</td>
            </tr>  
            {% endfor %}
          </tbody>
        </table>
      
      
      </div>
      
      <!-- Inizio Tab Valutazione-->
      <div class="tab-pane fade" id="valutazione-tab-pane" role="tabpanel" aria-labelledby="valutazione-tab" tabindex="0">
        <div class="row">
          <div class="col text-end">
            {% if form.instance.id  %}
              <a href="{% url 'human_resources:crea_valutazione_operatore' pk=humanresource.pk %}" class="btn btn-success mt-2 "><i class="bi bi-file-earmark-plus"></i> Aggiungi Valutazione</a>
            {% else %}
              <button class="btn btn-outline-success">Salvare per aggiungere</button>
            {% endif %}
          </div>
        </div>
        
        <div class="row">
          
        </div>
        {% if form.instance.id  %}
          <table class="table table-bordered table-striped mt-2">
            <thead>
              <tr>
                <th>Centro di Lavoro</th>            
                <th>Valutazione</th>
                <th>Azione</th>
              </tr>
            </thead>
            <tbody>
              
              {% for valutazione in elenco_valutazioni %}
              <tr>        
                
                <td><a href="{% url 'human_resources:modifica_valutazione_operatore' pk=humanresource.pk id=valutazione.pk %}">{{ valutazione.fk_centro_di_lavoro.description }}</a></td>
                <td>{{ valutazione.valutazione }}</td>                           
                <td class="text-center"><a href="{% url 'human_resources:delete_valutazione_operatore' pk=valutazione.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButton{{valutazione.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>             
              </tr>  
              {% endfor %}
            </tbody>
          </table>
        {% endif %}
      </div>
      <!-- Fine Tab Valutazione-->

      <!-- Inizio Tab Altri Incarichi-->
      <div class="tab-pane fade" id="incarichi-tab-pane" role="tabpanel" aria-labelledby="incarichi-tab" tabindex="0">
        <div class="row">
          <div class="col text-end">
            {% if form.instance.id  %}
              <a href="{% url 'human_resources:crea_hr_safety' pk=humanresource.pk %}" class="btn btn-success mt-2 "><i class="bi bi-file-earmark-plus"></i> Aggiungi Incarico Sicurezza</a>
            {% else %}
              <button class="btn btn-outline-success">Salvare per aggiungere</button>
            {% endif %}
          </div>
        </div>
        
        <div class="row">
          
        </div>
        {% if form.instance.id  %}
          <table class="table table-bordered table-striped mt-2">
            <thead>
              <tr>
                <th>Incarico Sicurezza</th>            
                <th>Data Inizio Incarico</th>
                <th>Data Fine Incarico</th>
                <th>Azione</th>
              </tr>
            </thead>
            <tbody>
              
              {% for incarico_sicurezza in elenco_incarichi_sicurezza %}
              <tr>        
                
                <td><a href="{% url 'human_resources:modifica_hr_safety' pk=incarico_sicurezza.pk %}">{{ incarico_sicurezza.fk_safety_role.descrizione }}</a></td>
                <td>{{ incarico_sicurezza.data_inizio_incarico }}</td>                           
                <td>{{ incarico_sicurezza.data_fine_incarico|default_if_none:"" }}</td>                           
                <td class="text-center"><a href="{% url 'human_resources:delete_hr_safety' pk=incarico_sicurezza.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButtonIncarico{{incarico_sicurezza.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>             
              </tr>  
              {% endfor %}
            </tbody>
          </table>
        {% endif %}
      </div>
      <!-- Fine Tab Altri Incarichi-->
      
    </div>
    

    

        


</div>

{% endblock %}

{% block extra_scripts %}
<script>

$(document).ready(function() {
  handleImagePreview('id_immagine', 'preview-image');
});

</script>

{% endblock %}

backend/human_resources/templates/human_resources/tabelle_generiche_hr.html
{% extends 'core/base.html' %} 
{% load static %}
{% load crispy_forms_tags %} 
{% load widget_tweaks %}
{% block head_title %}{{ block.super }} - Human Resources{% endblock head_title %} 

{% block sidenav %}
{% include "core/partials/_sidenav_human_resources.html" %}
{% endblock %}

{% block content %}
{% include 'core/modals/delConfirm.html' %}
<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>      
        <li class="breadcrumb-item"><a href="{% url 'human_resources:human_resources' %}">Operatori</a></li>     
        <li class="breadcrumb-item active" aria-current="page">Tabelle Generiche</li>        
    </ol>

</nav>
<div class="container">
  <br>
  <h3>Tabelle Generiche</h3>
  <hr>

  {% include "core/partials/_messages.html" %}


  <div class="row">
    <div class="col-6">
      <div class="row">
        <div class="col-6">
          <h5>Reparti</h5>          
        </div>
        <div class="col-6 text-end">
          <a href="{% url 'human_resources:create_ward' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Reparto</a>
        </div>
      </div>
      <div class="table-container">
        <table class="table table-bordered table-striped mt-2">
          <thead>
            <tr>
              <th>Descrizione</th>            
              <th>Azione</th>
              
            </tr>
          </thead>
          <tbody>
            {% for ward in wards %}
            <tr>        
              
              <td><a href="{% url 'human_resources:update_ward' pk=ward.pk %}">{{ ward.description }}</a></td>
              
              <td class="text-center"><a href="{% url 'human_resources:delete_ward' pk=ward.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButtonWard{{ward.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
            </tr>  
            {% endfor %}
          </tbody>
        </table>
        </div>
    </div>

    <div class="col-6">
      <div class="row">
        <div class="col-6">
          <h5>Mansioni</h5>
        </div>
        <div class="col-6 text-end">
          <a href="{% url 'human_resources:create_role' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Mansione</a>
        </div>
      </div>
      <div class="table-container">
        <table class="table table-bordered table-striped mt-2">
          <thead>
            <tr>
              <th>Descrizione</th>            
              <th>Azione</th>
              
            </tr>
          </thead>
          <tbody>
            {% for role in roles %}
            <tr>        
              
              <td><a href="{% url 'human_resources:update_role' pk=role.pk %}">{{ role.description }}</a></td>
              
              <td class="text-center"><a href="{% url 'human_resources:delete_role' pk=role.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButtonRole{{role.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
            </tr>  
            {% endfor %}
          </tbody>
        </table>
        </div>
    </div>

  </div>
  <div class="row mt-3">
  <!-- Inizio Centro di Lavoro -->
    <div class="col-6">
      <div class="row">
        <div class="col-6">
          <h5>Centri di Lavoro</h5>          
        </div>
        <div class="col-6 text-end">
          <a href="{% url 'human_resources:crea_centro_di_lavoro' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Centro di Lavoro</a>
        </div>
      </div>
      <div class="table-container">
        <table class="table table-bordered table-striped mt-2">
          <thead>
            <tr>
              <th>Descrizione</th>            
              <th>Azione</th>
              
            </tr>
          </thead>
          <tbody>
            {% for centrodilavoro in centridilavoro %}
            <tr>        
              
              <td><a href="{% url 'human_resources:modifica_centro_di_lavoro' pk=centrodilavoro.pk %}">{{ centrodilavoro.description }}</a></td>
              
              <td class="text-center"><a href="{% url 'human_resources:delete_centro_di_lavoro' pk=centrodilavoro.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButtonCentroLavoro{{centrodilavoro.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
            </tr>  
            {% endfor %}
          </tbody>
        </table>
        </div>
    </div>
    <!-- Fine Centro di Lavoro -->

    <!-- Inizio Safety Roles -->
    <div class="col-6">
      <div class="row">
        <div class="col-6">
          <h5>Incarichi Sicurezza</h5>          
        </div>
        <div class="col-6 text-end">
          <a href="{% url 'human_resources:create_safety_role' %}" class="btn btn-sm btn-success"><i class="bi bi-file-earmark-plus"></i> Aggiungi Incarico Sicurezza</a>
        </div>
      </div>
      <div class="table-container">
        <table class="table table-bordered table-striped mt-2">
          <thead>
            <tr>
              <th>Descrizione</th>            
              <th>Azione</th>
              
            </tr>
          </thead>
          <tbody>
            {% for safety_role in safety_roles %}
            <tr>        
              
              <td><a href="{% url 'human_resources:update_safety_role' pk=safety_role.pk %}">{{ safety_role.descrizione }}</a></td>
              
              <td class="text-center"><a href="{% url 'human_resources:delete_safety_role' pk=safety_role.pk %}" class="btn btn-sm btn-outline-danger confirm-delete" title="Delete" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal" id="deleteButtonSafetyRole{{safety_role.pk}}"><i class="bi bi-trash"></i>Elimina</a></td>
            </tr>  
            {% endfor %}
          </tbody>
        </table>
        </div>
    </div>
    <!-- Fine Safety Roles -->


  </div>
</div>

{% endblock content %}