backend/air_emissions/urls.py
from django.urls import path

from .views import *

app_name="air_emissions"



urlpatterns = [

    
    # Dashboard
    path("dashboard/", dashboard_emissions, name="dashboard_emissions"),

    # Punti di Emissione
    path("aggiungi_punto_emissione/", PuntoEmissioneCreateView.as_view(), name="aggiungi_punto_emissione"),
    path("modifica_punto_emissione/<int:pk>", PuntoEmissioneUpdateView.as_view(), name="modifica_punto_emissione"),
    path("delete_punto_emissione/<int:pk>", delete_punto_emissione, name="delete_punto_emissione"),
    
    # Registro Analisi
    path("<int:fk_punto_emissione>/aggiungi_registro_analisi/", RegistroControlloAnaliticoCreateView.as_view(), name="aggiungi_registro_analisi"),
    path("<int:fk_punto_emissione>/modifica_registro_analisi/<int:pk>", RegistroControlloAnaliticoUpdateView.as_view(), name="modifica_registro_analisi"),
    path("delete_registro_analisi/<int:pk>", delete_registro_analisi, name="delete_registro_analisi"),

    # Stampe
    path("registro_controlli_analitici/", registro_controlli_analitici, name="registro_controlli_analitici"),
    

    
]

backend/anagrafiche/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .api import ClienteViewSet, FornitoreViewSet
from .charts import get_country_count, get_country_count_client
from .views import *

app_name = "anagrafiche"


router = DefaultRouter()
router.register("clienti", ClienteViewSet)
router.register("fornitori", FornitoreViewSet)


urlpatterns = [
    # Facility
    path(
        "aggiungi_facility_details/",
        FacilityCreateView.as_view(),
        name="aggiungi_facility_details",
    ),
    path(
        "edit_facility_details/<int:pk>/",
        FacilityUpdateView.as_view(),
        name="edit_facility_details",
    ),
    path(
        "<int:pk>/add_facility_contact",
        add_facility_contact,
        name="add_facility_contact",
    ),
    path(
        "<int:pk>/modifica_facility_contact/<int:id>",
        FacilityContactUpdateView.as_view(),
        name="modifica_facility_contact",
    ),
    path(
        "delete_facility_contact/<int:pk>",
        delete_facility_contact,
        name="delete_facility_contact",
    ),
    # path("<int:fk_facility>/home_autorizzazioni/", home_autorizzazioni, name="home_autorizzazioni"),
    # path("<int:fk_facility>/add_facility_authorization/", FacilityAuthorizationCreateView.as_view(), name="add_facility_authorization"),
    # path("<int:fk_facility>/modifica_facility_authorization/<int:id>", FacilityAuthorizationUpdateView.as_view(), name="modifica_facility_authorization"),
    # path("delete_facility_authorization/<int:pk>", delete_facility_authorization, name="delete_facility_authorization"),
    # Clienti
    path("home_clienti/", ListaClienteView.as_view(), name="home_clienti"),
    path("aggiungi_cliente/", ClienteCreateView.as_view(), name="aggiungi_cliente"),
    path(
        "modifica_cliente/<int:pk>",
        ClienteUpdateView.as_view(),
        name="modifica_cliente",
    ),
    # Fornitori
    path("home_fornitori/", home_fornitori, name="home_fornitori"),
    path("aggiungi_fornitore/", CreateSupplier.as_view(), name="aggiungi_fornitore"),
    path(
        "aggiungi_fornitore_with_category/<str:category>/",
        aggiungi_fornitore_with_category,
        name="aggiungi_fornitore_with_category",
    ),
    path("vedi_fornitore/<int:pk>", UpdateSupplier.as_view(), name="vedi_fornitore"),
    path(
        "fornitore/<int:fk_fornitore>/aggiungi_lwg/",
        AddLwgCertificate.as_view(),
        name="aggiungi_lwg",
    ),
    path("modifica_lwg/<int:pk>", UpdateLwgCertificate.as_view(), name="modifica_lwg"),
    path("delete_lwg/<int:pk>", delete_certificato, name="delete_lwg"),
    path(
        "modifica_lwg/<int:fk_certificato>/add_transf_value/",
        XrTransferValueCreateView.as_view(),
        name="add_transf_value",
    ),
    path(
        "edit_transf_value/<int:pk>",
        XrTransferValueUpdateView.as_view(),
        name="edit_transf_value",
    ),
    path(
        "delete_transf_value/<int:pk>",
        delete_xrtransfervalue,
        name="delete_transf_value",
    ),
    # Listino terzisti
    path(
        "fornitore/<int:fk_fornitore>/aggiungi_voce_listino/",
        ListinoTerzistaCreateView.as_view(),
        name="aggiungi_voce_listino",
    ),
    path(
        "modifica_voce_listino/<int:pk>",
        ListinoTerzistaUpdateView.as_view(),
        name="modifica_voce_listino",
    ),
    path(
        "delete_voce_listino/<int:pk>", delete_voce_listino, name="delete_voce_listino"
    ),
    path(
        "<int:fk_listino_terzista>/aggiungi_prezzo_listino/",
        PrezzoListinoCreateView.as_view(),
        name="aggiungi_prezzo_listino",
    ),
    path(
        "modifica_prezzo_listino/<int:pk>",
        PrezzoListinoUpdateView.as_view(),
        name="modifica_prezzo_listino",
    ),
    path(
        "delete_prezzo_listino/<int:pk>",
        delete_prezzo_listino,
        name="delete_prezzo_listino",
    ),
    # Gestori Rifiuti
    path(
        "fornitore/<int:fk_fornitore>/aggiungi_gestore_rifiuti/",
        XrDocumentiGestoreCreateView.as_view(),
        name="aggiungi_gestore_rifiuti",
    ),
    path(
        "modifica_gestore_rifiuti/<int:pk>",
        XrDocumentiGestoreUpdateView.as_view(),
        name="modifica_gestore_rifiuti",
    ),
    path(
        "delete_gestore_rifiuti/<int:pk>",
        delete_gestore_rifiuti,
        name="delete_gestore_rifiuti",
    ),
    # Listino Clienti
    path(
        "cliente/<int:fk_cliente>/aggiungi_voce_listino_cliente/",
        ListinoClienteCreateView.as_view(),
        name="aggiungi_voce_listino_cliente",
    ),
    path(
        "modifica_voce_listino_cliente/<int:pk>",
        ListinoClienteUpdateView.as_view(),
        name="modifica_voce_listino_cliente",
    ),
    path(
        "delete_voce_listino_cliente/<int:pk>",
        delete_voce_listino_cliente,
        name="delete_voce_listino_cliente",
    ),
    # Tabelle Generiche
    path("tabelle_generiche/", tabelle_generiche, name="tabelle_generiche"),
    # Generiche - Transfer Values
    path(
        "add_transfer_values/",
        TransferValueCreateView.as_view(),
        name="add_transfer_values",
    ),
    path(
        "edit_transfer_values/<int:pk>",
        TransferValueUpdateView.as_view(),
        name="edit_transfer_values",
    ),
    path(
        "delete_transfer_value/<int:pk>",
        delete_transfer_value,
        name="delete_transfer_value",
    ),
    # Charts
    path("get_country_count/", get_country_count, name="get_country_count"),
    path(
        "get_country_count_client/",
        get_country_count_client,
        name="get_country_count_client",
    ),
    # API
    path("", include(router.urls)),
]

backend/articoli/urls.py
from django.urls import path

from .utils import *
from .views import *

app_name="articoli"



urlpatterns = [

    # Home Articoli
    path("", articoli_home, name="articoli_home"),    
    path("crea_articolo/", ArticoloCreateView.as_view(), name="crea_articolo"),    
    path("modifica_articolo/<int:pk>", ArticoloUpdateView.as_view(), name="modifica_articolo"),    
    path("delete_articolo/<int:pk>", delete_articolo, name="delete_articolo"), 
    
    # Home Colori
    path("colori/", colori_home, name="colori_home"),    
    path("colori/crea_colore/", ColoreCreateView.as_view(), name="crea_colore"),    
    path("colori/modifica_colore/<int:pk>", ColoreUpdateView.as_view(), name="modifica_colore"),    
    path("colori/delete_colore/<int:pk>", delete_colore, name="delete_colore"),    
    
    # Tabelle Generiche
    path("tabelle_generiche/", tabelle_generiche, name="tabelle_generiche"),

    # Fasi di Lavoro       
    path("crea_fase_lavoro/", FaseLavoroCreateView.as_view(), name="crea_fase_lavoro"),    
    path("modifica_fase_lavoro/<int:pk>", FaseLavoroUpdateView.as_view(), name="modifica_fase_lavoro"),    
    path("delete_fase_lavoro/<int:pk>", delete_fase_lavoro, name="delete_fase_lavoro"), 

    # Attributo fasi di lavoro
    path('<int:fk_fase_lavoro>/aggiungi_attributo/', DettaglioFaseLavoroCreateView.as_view(), name="aggiungi_attributo"), 
    path('<int:fk_fase_lavoro>/modifica_attributo/<int:pk>/', DettaglioFaseLavoroUpdateView.as_view(), name="modifica_attributo"), 
    path('delete_attributo/<int:pk>', delete_dettaglio_fase_lavoro, name="delete_attributo"),
    
    # Lavorazioni Esterne      
    path("crea_lavorazione_esterna/", LavorazioneEsternaCreateView.as_view(), name="crea_lavorazione_esterna"),    
    path("modifica_lavorazione_esterna/<int:pk>", LavorazioneEsternaUpdateView.as_view(), name="modifica_lavorazione_esterna"),    
    path("delete_lavorazione_esterna/<int:pk>", delete_lavorazione_esterna, name="delete_lavorazione_esterna"), 

    # Elenco Test      
    path("crea_test/", ElencoTestCreateView.as_view(), name="crea_test"),    
    path("modifica_test/<int:pk>", ElencoTestUpdateView.as_view(), name="modifica_test"),    
    path("delete_test/<int:pk>", delete_test, name="delete_test"), 

    # Test Articolo
    path('<int:fk_articolo>/aggiungi_test_articolo/', TestArticoloCreateView.as_view(), name="aggiungi_test_articolo"), 
    path('<int:fk_articolo>/modifica_test_articolo/<int:pk>/', TestArticoloUpdateView.as_view(), name="modifica_test_articolo"), 
    path('delete_test_articolo/<int:pk>', delete_test_articolo, name="delete_test_articolo"),
    
    # Procedura
    path('<int:fk_articolo>/aggiungi_procedura/', ProceduraCreateView.as_view(), name="aggiungi_procedura"), 
    path('<int:fk_articolo>/modifica_procedura/<int:pk>/', ProceduraUpdateView.as_view(), name="modifica_procedura"), 
    path('delete_procedura/<int:pk>', delete_procedura, name="delete_procedura"),
    
    # Dettaglio Procedura
    path('<int:fk_procedura>/aggiungi_dettaglio_procedura/', DettaglioProceduraCreateView.as_view(), name="aggiungi_dettaglio_procedura"), 
    path('<int:fk_procedura>/modifica_dettaglio_procedura/<int:pk>/', DettaglioProceduraUpdateView.as_view(), name="modifica_dettaglio_procedura"), 
    path('delete_dettaglio_procedura/<int:pk>', delete_dettaglio_procedura, name="delete_dettaglio_procedura"),

    # Caratteristica Procedura
    path('<int:fk_dettaglio_procedura>/aggiungi_caratteristica_procedura/', CaratteristicaProceduraCreateView.as_view(), name="aggiungi_caratteristica_procedura"), 
    path('<int:fk_dettaglio_procedura>/modifica_caratteristica_procedura/<int:pk>/', CaratteristicaProceduraUpdateView.as_view(), name="modifica_caratteristica_procedura"), 
    path('delete_caratteristica_procedura/<int:pk>', delete_caratteristica_procedura, name="delete_caratteristica_procedura"),

    # Automatismi
    path('accoda_dettaglio_fase_lavoro/', accoda_dettaglio_fase_lavoro, name="accoda_dettaglio_fase_lavoro"),
    path('accoda_caratteristiche_fase_lavoro_dettaglio_procedura/', accoda_caratteristiche_fase_lavoro_dettaglio_procedura, name="accoda_caratteristiche_fase_lavoro_dettaglio_procedura"),

    # Stampe
    path('stampa_procedura/<int:pk>/', stampa_procedura, name='stampa_procedura'),

    
]

backend/core/urls.py
from core.views import dashboard
from django.urls import path

from .dash_charts import *
from .searches import *
from .utils import update_row_numbers
from .dash_charts import produzione, energia, gas

app_name="core"

urlpatterns = [
    
    path('dashboard/', dashboard, name='dashboard'),    
      
    
    path('update_row_numbers/<str:app_name>/<str:model_name>/', update_row_numbers, name='update_row_numbers'),



    # Ricerche
    path('search_articolo/', search_articolo, name='search_articolo'),
    path('search_colore/', search_colore, name='search_colore'),
    path('search_revisione_rifinizione/', search_revisione_rifinizione, name='search_revisione_rifinizione'),
    path('search_revisione_colore_rifinizione/', search_revisione_colore_rifinizione, name='search_revisione_colore_rifinizione'),
    path('search_prodotto_chimico/', search_prodotto_chimico, name='search_prodotto_chimico'),
    path('search_ghs_symbol/', search_ghs_symbol, name='search_ghs_symbol'),
    path('search_hazard_statement/', search_hazard_statement, name='search_hazard_statement'),
    path('search_precautionary_statement/', search_precautionary_statement, name='search_precautionary_statement'),
    path('search_chem_supplier/', search_chem_supplier, name='search_chem_supplier'),
    path('search_supplier/', search_supplier, name='search_supplier'),
    path('search_outsourcing/', search_outsourcing, name='search_outsourcing'),

    path('search_revisione_bagnato/', search_revisione_bagnato, name="search_revisione_bagnato"), # Ricette Bagnato
    path('search_revisione_colore_bagnato/', search_revisione_colore_bagnato, name="search_revisione_colore_bagnato"), # Ricette Colore Bagnato


    path('search_fase_lavoro/', search_fase_lavoro, name="search_fase_lavoro"), # Fase lavoro
    
    
    #Grafici dashboard
    #path('produzione_intervallo_date/', produzione_intervallo_date, name="produzione_intervallo_date"),
    path('produzione/', produzione, name="produzione"),
    path('energia/', energia, name="energia"),
    path('gas/', gas, name="gas"),

       
     
]

backend/lwg/urls.py
from django.urls import path
from lwg.views import (lwg_home, lwg_procedure, scadenzario_completo
                                    )

app_name="lwg"

urlpatterns = [
    
    # Home LWG
    path('', lwg_home, name='lwg_home'),
    
    #LWG Procedure    
    path('lwg_procedure/<int:fk_lwgsection>', lwg_procedure, name='lwg_procedure'),

    # Scadenzario    
    path('scadenzario_completo/', scadenzario_completo, name='scadenzario_completo'),    

    
]

backend/qmsproject/urls.py
from core.views import home
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path("", home, name="home"),
    path("core/", include("core.urls")),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("anagrafiche/", include("anagrafiche.urls")),
    path("human_resources/", include("human_resources.urls")),
    path("acquistopelli/", include("acquistopelli.urls")),
    path("articoli/", include("articoli.urls")),
    path("manualeprocedure/", include("manualeprocedure.urls")),
    path("monitoraggi/", include("monitoraggi.urls")),
    path("manutenzioni/", include("manutenzioni.urls")),
    path("lwg/", include("lwg.urls")),
    path("autorizzazioni/", include("autorizzazioni.urls")),
    path("gestionerifiuti/", include("gestionerifiuti.urls")),
    path("nonconformity/", include("nonconformity.urls")),
    path("chem_man/", include("chem_man.urls")),
    path("antincendio/", include("antincendio.urls")),
    path("ricette/", include("ricette.urls")),
    path("air_emissions/", include("air_emissions.urls")),
    path("vendite/", include("vendite.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    # API
    path("api/accounts/", include("accounts.urls")),
    path("api/anagrafiche/", include("anagrafiche.urls")),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/vendite/urls.py
from django.urls import path

from .views import *

app_name = "vendite"

urlpatterns = [
    # Home Ordini Cliente
    path("", home_ordini_cliente, name="home_ordini_cliente"),
    path("aggiungi_ordine_cliente/", OrdineClienteCreateView.as_view(), name="aggiungi_ordine_cliente"),
    path("modifica_ordine_cliente/<int:pk>/", OrdineClienteUpdateView.as_view(), name="modifica_ordine_cliente"),
    path(
        "modifica_ordine_cliente_with_focus_button/<int:pk>/<str:focus_button>/",
        OrdineClienteUpdateView.as_view(),
        name="modifica_ordine_cliente_with_focus_button",
    ),
    path('delete_ordine_cliente/<int:pk>',
        delete_ordine_cliente,
        name="delete_ordine_cliente"),  

    path("<int:fk_ordine>/aggiungi_dettaglio_ordine/", DettaglioOrdineClienteCreateView.as_view(), name="aggiungi_dettaglio_ordine"),
    path("<int:fk_ordine>/modifica_dettaglio_ordine/<int:pk>", DettaglioOrdineClienteUpdateView.as_view(), name="modifica_dettaglio_ordine"),
    path('delete_dettaglio_ordine_cliente/<int:pk>',
        delete_dettaglio_ordine_cliente,
        name="delete_dettaglio_ordine_cliente"),  
    
    path("schede_lavorazione/", home_schede_lavorazione, name="home_schede_lavorazione"),
    path("aggiungi_scheda_lavorazione/", SchedaLavorazioneCreateView.as_view(), name="aggiungi_scheda_lavorazione"),
    path("modifica_scheda_lavorazione/<int:pk>/", SchedaLavorazioneUpdateView.as_view(), name="modifica_scheda_lavorazione"),
    path(
        "modifica_scheda_lavorazione_with_focus_button/<int:pk>/<str:focus_button>/",
        OrdineClienteUpdateView.as_view(),
        name="modifica_scheda_lavorazione_with_focus_button",
    ),
    path('delete_scheda_lavorazione/<int:pk>',
        delete_scheda_lavorazione,
        name="delete_scheda_lavorazione"),  

    path("<int:fk_schedalavorazione>/aggiungi_dettaglio_scheda/", XRScelteSchedeCreateView.as_view(), name="aggiungi_dettaglio_scheda"),
    path("<int:fk_schedalavorazione>/modifica_dettaglio_scheda/<int:pk>", XRScelteSchedeUpdateView.as_view(), name="modifica_dettaglio_scheda"),
    path('delete_dettaglio_scheda/<int:pk>',
        delete_dettaglio_scheda,
        name="delete_dettaglio_scheda"),  

    path('xrscelte/nuova/', XRScelteSchedeCreateView.as_view(), name="nuova_xrscelta"),
    path('xrscelte/<int:pk>/modifica/', XRScelteSchedeUpdateView.as_view(), name="modifica_xrscelta"),
]

backend/core/templates/core/home.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}QMS {% endblock %}

{% block sidenav %}
{% include "core/partials/_sidenav_base.html" %}
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row mt-4">
      
        <div class="col-4">
          <div class="card" >
              
             
                <div class="card-body">
                  <h5 class="card-title"><i class="bi bi-person-vcard"></i> Anagrafiche</h5>
                  <hr>
                  <p class="card-text">Aggiorna, elimina e visualizza le informazioni dettagliate di clienti e fornitori.</p>
                  <a href="{% url 'anagrafiche:home_clienti' %}" class="btn btn-sm btn-primary">Sezione Clienti</a>
                  <a href="{% url 'anagrafiche:home_fornitori' %}" class="btn btn-sm btn-primary">Sezione Fornitori</a>
                  
                </div>
              </div>
              
        </div>

        <div class="col-4">
            <div class="card" >
                <div class="card-body">
                  <h5 class="card-title"><i class="bi bi-archive"></i> Articoli</h5>
                  <hr>
                  <p class="card-text">Esplora, crea, modifica ed elimina gli articoli.</p>
                  <a href="{% url 'articoli:articoli_home' %}" class="btn btn-sm btn-primary">Vai alla sezione</a>
                  
                </div>
              </div>
        </div>

        <div class="col-4">
            <div class="card" >
                <div class="card-body">
                  <h5 class="card-title"><i class="bi bi-person-workspace"></i> Risorse Umane</h5>
                  <hr>
                  <p class="card-text">Gestisci il personale, gli incarichi e la formazione aziendale.</p>
                  <a href="{% url 'human_resources:human_resources' %}" class="btn btn-sm btn-primary">Vai alla sezione</a>
                  {% if scadenze_formazione > 0 %}
        
                    <button onclick="goToTrainingSchedule()" type="button" class="btn btn-primary btn-sm position-relative float-end ">
                        Prossime scadenze
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                            {{ scadenze_formazione }}
                        <span class="visually-hidden">Prossime scadenze</span>
                        </span>
                    </button>
                  {% endif %}
                </div>
              </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-4">
            <div class="card" >
                <div class="card-body">
                  <h5 class="card-title"><i class="bi bi-box-arrow-in-down-left"></i> Acquisti</h5>
                  <hr>

                  <p class="card-text">Gestisci l'approvvigionamento delle materie prime.</p>
                  <a href="{% url 'acquistopelli:dashboard_acquisto_pelli' %}" class="btn btn-sm btn-primary">Vai alla sezione</a>
                  
                </div>
              </div>
        </div>

        <div class="col-4">
            <div class="card" >
                <div class="card-body">
                  <h5 class="card-title"><i class="bi bi-box-arrow-up-right"></i> Vendite</h5>
                  <hr>
                  <p class="card-text">Gestisci vendite e messa in lavoro aziendale.</p>
                  <a href="{% url 'vendite:home_ordini_cliente' %}" class="btn btn-sm btn-primary">Vai alla sezione</a>
                  
                </div>
              </div>
        </div>

        <div class="col-4">
            <div class="card" >
                <div class="card-body">
                  <h5 class="card-title">Lavorazioni</h5>
                  <hr>
                  <p class="card-text">Elenco lavorazioni e listini prezzi lavorazioni.</p>
                  <a href="#" class="btn btn-sm btn-secondary">Vai alla sezione</a>
                  
                </div>
              </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-4">
            <div class="card" >
                <div class="card-body">
                  <h5 class="card-title"><i class="bi bi-moisture"></i> Gestione Chimica</h5>
                  <hr>
                  <p class="card-text">Massimizza la sicurezza e l'efficienza nella gestione dei prodotti chimici.</p>
                  <a href="{% url 'chem_man:home_prodotti_chimici' %}" class="btn btn-sm btn-primary">Vai alla sezione</a>
                  
                </div>
              </div>
        </div>

        <div class="col-4">
            <div class="card" >
                <div class="card-body">
                  <h5 class="card-title"><i class="bi bi-speedometer"></i> Monitoraggi</h5>
                  <hr>
                  <p class="card-text">Misura e monitora l'efficienza energetica dei processi.</p>
                  <a href="{% url 'monitoraggi:dashboard_monitoraggi' %}" class="btn btn-sm btn-primary">Vai alla sezione</a>
                  
                </div>
              </div>
        </div>

        <div class="col-4">
            <div class="card" >
                <div class="card-body">
                  <h5 class="card-title"><i class="bi bi-wrench"></i> Manutenzioni e controlli periodici</h5>
                  <hr>
                  <p class="card-text">Programma e monitora le manutenzioni ordinarie, straordinarie e i controlli periodici. </p>
                  <a href="{% url 'manutenzioni:dashboard_manutenzioni' %}" class="btn btn-sm btn-primary">Vai alla sezione</a>
                  {% if scadenze_manutenzioni > 0 %}
        
                    <button onclick="goToMaintenanceSchedule()" type="button" class="btn btn-primary btn-sm position-relative float-end ">
                        Prossime scadenze
                        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                            {{ scadenze_manutenzioni }}
                        <span class="visually-hidden">Prossime scadenze</span>
                        </span>
                    </button>
                  {% endif %}
                  
                </div>
              </div>
        </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-4">
          <div class="card" >
              <div class="card-body">
                <h5 class="card-title"><i class="bi bi-book"></i> Manuale Procedure</h5>
                <hr>
                <p class="card-text">Standardizza e documenta le procedure aziendali per una maggiore efficienza.</p>
                <a href="{% url 'manualeprocedure:procedure_home' %}" class="btn btn-sm btn-primary">Vai alla sezione</a>
                
              </div>
            </div>
      </div>

      <div class="col-4">
        <div class="card" >
            <div class="card-body">
              <h5 class="card-title"><i class="bi bi-recycle"></i> Gestione Rifiuti</h5>
              <hr>
              <p class="card-text">Traccia e gestisci la raccolta, il trattamento e lo smaltimento dei rifiuti.</p>
              <a href="{% url 'gestionerifiuti:gestione_rifiuti_home' %}" class="btn btn-sm btn-primary">Vai alla sezione</a>
              
            </div>
          </div>
    </div>

    <div class="col-4">
      <div class="card" >
          <div class="card-body">
            <h5 class="card-title"><i class="bi bi-fire"></i> Prevenzione Incendi</h5>
            <hr>
            <p class="card-text">Registro dei mezzi di prevenzione incendi e controlli periodici.</p>
            <a href="{% url 'antincendio:antincendio_home' %}" class="btn btn-sm btn-primary">Vai alla sezione</a>
            
          </div>
        </div>
  </div>

    

      
  </div>
  <hr>
  <div class="row">
    <div class="col-4">
      <div class="card" >
          <div class="card-body">
            <h5 class="card-title"><i class="bi bi-journal-check"></i> Registro Non Conformità</h5>
            <hr>
            <p class="card-text">Documenta e traccia le azioni correttive e preventive.</p>
            <a href="{% url 'nonconformity:home_rapporti_nc' %}" class="btn btn-sm btn-primary">Vai alla sezione</a>
            
          </div>
        </div>
  </div>

  <div class="col-4">
      <div class="card" >
          <div class="card-body">
            <h5 class="card-title"><i class="bi bi-wind"></i> Emissioni in Atmosfera</h5>
            <hr>
            <p class="card-text">Inventario Punti di Emissioni e analisi.</p>
            <a href="{% url 'air_emissions:dashboard_emissions' %}" class="btn btn-sm btn-primary">Vai alla sezione</a>
            
          </div>
        </div>
  </div>

  </div>
</div>
{% endblock %}

{% block extra_scripts %}
<script>
function goToMaintenanceSchedule(){
        document.location.href = "{% url 'manutenzioni:scadenzario' %}"        
    }
  
function goToTrainingSchedule(){
        document.location.href = "{% url 'human_resources:scadenzario' %}"        
    }


</script>
{% endblock %}